SUPABASE_URL = "https://your-project.supabase.co"
SUPABASE_SECRET_KEY = "sb_secret_your-key-here"
LABELS_JSONL_BACKUP = "0"  # set to 1 if you want JSONL backups while developing
# Optional overrides (defaults shown below are for container deployments)
LABELER_DATA_DIR = "data"
LABELS_OUTPUT_DIR = "data/labels"
MAX_ANNOTATORS_PER_REQUEST = "2"
REVIEWER_EMAILS = "reviewer@example.org,another@example.org"

[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "generate-a-long-random-string"
client_id = "auth0-client-id"
client_secret = "auth0-client-secret"
server_metadata_url = "https://your-tenant.us.auth0.com/.well-known/openid-configuration"
