SUPABASE_URL = "https://your-project.supabase.co"
SUPABASE_ANON_KEY = "your-anon-key"
LABELS_JSONL_BACKUP = "0"
LABELER_DATA_DIR = "/app/data"
LABELS_OUTPUT_DIR = "/app/data/labels"
MAX_ANNOTATORS_PER_REQUEST = "3"
