SUPABASE_URL = "https://your-project.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_your-key-here"
LABELS_JSONL_BACKUP = "0"  # set to 1 if you want JSONL backups while developing
# Optional overrides (defaults shown below are for container deployments)
LABELER_DATA_DIR = "data"
LABELS_OUTPUT_DIR = "data/labels"
MAX_ANNOTATORS_PER_REQUEST = "3"
